# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!
target 'TouchID_IOS' do
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SwiftKeychainWrapper'

end
